### ISSUE TITLE
The example doesn't work in Firefox

### ISSUE THREAD

**Issue by nodefourtytwo** [maximebf/gousse.js#1]
I use FF62 and the example todo app gives me a blank page with "component(): Custom elements are not available, all components fallback to JS definition only" in the console.

**Comment by maximebf** [comment]
In Firefox, Web Components are not enabled by default yet. To do so follow these instructions: https://www.designedbyaturtle.co.uk/2015/how-to-enable-web-components-in-firefox-shadow-dom/

They will be enabled by default in the next version (63)
